# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: ROS-CI

# This determines when this workflow is run
on: [push, pull_request] # on all pushes and PRs

jobs:
  CI:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic}
          - {ROS_DISTRO: iron}
          - {ROS_DISTRO: humble}
          #- {ROS_DISTRO: rolling}
    env:
      #CCACHE_DIR: /github/home/.ccache # Enable ccache
      BUILDER: colcon
      PRERELEASE: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # This step will fetch/store the directory used by ccache before/after the ci run
      #- uses: actions/cache@v3
      #  with:
      #    path: ${{ env.CCACHE_DIR }}
      #    key: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@9f963f67ebb889792175776c5ee00134d7bb569b'
        env: ${{ matrix.env }}

  check:
    if: always()
    name: check-ros-ci

    needs:
    - CI

    runs-on: Ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
